Repository ocadotechnology/aimmo, pull requests merged in 2018-12, with the labels that each got.

#908 Add .vscode to the .gitignore
  .gitignore
Labels: enhancement

#916 Update react and babel
  game_frontend/.babelrc
  game_frontend/package.json
  game_frontend/src/components/GameView/__snapshots__/index.test.js.snap
  game_frontend/src/components/GameView/index.test.js
  game_frontend/src/index.js
  game_frontend/yarn.lock
  version.txt
  yarn.lock
Labels: Development

#936 Button hotfix
  game_frontend/src/components/RunCodeButton/index.js
  game_frontend/yarn.lock
  version.txt
Labels: Hot fix!, bug
