Repository ocadotechnology/aimmo, pull requests merged in 2018-08, with the labels that each got.

#695 Fix local non -k mode
  aimmo/game_renderer.py
Labels: Development, bug

#707 Leaking data structures between tests
  aimmo-game/service.py
  aimmo-game/simulation/game_state_provider.py
  aimmo-game/simulation/logs_provider.py
  aimmo-game/simulation/turn_manager.py
  aimmo-game/tests/functional/mock_world.py
  aimmo-game/tests/test_service.py
  aimmo-game/tests/test_simulation/fake_game_runner.py
Labels: bug, enhancement

#711 Leaking data structures + gotcha fix
  aimmo-game/service.py
  aimmo-game/simulation/game_state_provider.py
  aimmo-game/simulation/logs_provider.py
  aimmo-game/simulation/turn_manager.py
  aimmo-game/tests/functional/mock_world.py
  aimmo-game/tests/test_service.py
  aimmo-game/tests/test_simulation/fake_game_runner.py
  aimmo-game/tests/test_simulation/test_turn_manager.py
Labels: Development, bug, enhancement

#699 Back-end python socket tests & minor refactoring
  aimmo-game/service.py
  aimmo-game/simulation/game_logic/map_updaters.py
  aimmo-game/simulation/logs_provider.py
  aimmo-game/simulation/turn_manager.py
  aimmo-game/tests/test_service.py
  aimmo-game/tests/test_socketio.py
  docs/architecture/workers/README.md
Labels: Development, testing

#713 update material-ui and update theme
  game_frontend/package.json
  game_frontend/src/theme.js
  game_frontend/yarn.lock
Labels: Development, UX/UI

#715 Remove pykube dependency
  Pipfile.lock
  aimmo-game-creator/game_manager.py
  aimmo-game-creator/requirements.txt
  aimmo-game-creator/setup.py
  aimmo-game-worker/requirements.txt
  aimmo-game/requirements.txt
  aimmo-game/setup.py
  aimmo-game/simulation/worker_managers/kubernetes_worker_manager.py
  aimmo/setup.py
  aimmo_runner/setup.py
  setup.py
Labels: Development, enhancement

#728 Task issue template
  .github/ISSUE_TEMPLATE/new_task.md
Labels: Documentation

#747 Remove obsolete example code (ghibli)
  game_frontend/src/index.js
  game_frontend/src/redux/features/GhibliMovies/actions.js
  game_frontend/src/redux/features/GhibliMovies/epics.js
  game_frontend/src/redux/features/GhibliMovies/epics.test.js
  game_frontend/src/redux/features/GhibliMovies/index.js
  game_frontend/src/redux/features/GhibliMovies/reducers.js
  game_frontend/src/redux/features/GhibliMovies/reducers.test.js
  game_frontend/src/redux/features/GhibliMovies/types.js
  game_frontend/src/redux/features/index.js
Labels: Development

#743 Refactor game service
  aimmo-game-worker/service.py
  aimmo-game-worker/simulation/avatar_state.py
  aimmo-game-worker/simulation/world_map.py
  aimmo-game/service.py
  aimmo-game/simulation/avatar/avatar_manager.py
  aimmo-game/simulation/avatar/avatar_wrapper.py
  aimmo-game/simulation/game_state.py
  aimmo-game/simulation/game_state_provider.py
  aimmo-game/simulation/logs.py
  aimmo-game/simulation/pickups.py
  aimmo-game/simulation/turn_manager.py
  aimmo-game/simulation/world_map.py
  aimmo-game/tests/functional/mock_world.py
  aimmo-game/tests/test_service.py
  aimmo-game/tests/test_simulation/dummy_avatar.py
  aimmo-game/tests/test_simulation/fake_game_runner.py
  aimmo-game/tests/test_simulation/test_logs.py
  aimmo-game/tests/test_simulation/test_turn_manager.py
  aimmo-game/tests/test_socketio.py
Labels: Development

#751 Fix #749 | Scrolling bug
  game_frontend/src/components/IDEConsole/index.js
Labels: Development, UX/UI, bug

#775 Update yarn.lock & snapshot test
  game_frontend/src/containers/IDE/__snapshots__/index.test.js.snap
  game_frontend/yarn.lock
Labels: Development
